name: YouTube Booster Run

on:
  schedule:
    - cron: '*/5 * * * *' # Se lance automatiquement toutes les 5 minutes
  workflow_dispatch:      # Permet de garder le bouton gris "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Recupere le code
        uses: actions/checkout@v2

      - name: Installe Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Installe les outils Selenium
        run: |
          pip install selenium webdriver-manager requests

      - name: Execution du Bot en Rafale
        run: |
          # Première rafale de 8 sessions (Parallèle)
          python bot_v1.py &
          python bot_v1.py &
          python bot_v1.py &
          python bot_v1.py &
          python bot_v1.py &
          python bot_v1.py &
          python bot_v1.py &
          python bot_v1.py &
          wait # Attend que la 1ère vague termine
          
          sleep 8
          
          # Deuxième rafale de 8 sessions (Parallèle)
          python bot_v1.py &
          python bot_v1.py &
          python bot_v1.py &
          python bot_v1.py &
          python bot_v1.py &
          python bot_v1.py &
          python bot_v1.py &
          python bot_v1.py &
          wait # Attend que la 2ème vague termine
